# Generated by Django 5.0.1 on 2024-08-12 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Collateral',
            fields=[
                ('collateral_id', models.AutoField(primary_key=True, serialize=False)),
                ('collateral_type', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('due_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_type', models.CharField(choices=[('Savings', 'Savings'), ('Checking', 'Checking'), ('Fixed Deposit', 'Fixed Deposit')], max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CheckingAccount',
            fields=[
                ('checking_account_id', models.AutoField(primary_key=True, serialize=False)),
                ('overdraft_limit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.account')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('position', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_of_hire', models.DateField()),
                ('department', models.CharField(max_length=100)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='polls.branch')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_branch', to='polls.employee'),
        ),
        migrations.CreateModel(
            name='FixedDepositAccount',
            fields=[
                ('fixed_deposit_id', models.AutoField(primary_key=True, serialize=False)),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('maturity_date', models.DateField()),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.account')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('repayment_schedule', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('collateral', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loan', to='polls.collateral')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavingsAccount',
            fields=[
                ('savings_account_id', models.AutoField(primary_key=True, serialize=False)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('accumulated_interest', models.DecimalField(decimal_places=2, max_digits=15)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.account')),
            ],
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('task_assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.employee')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.task')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('Deposit', 'Deposit'), ('Withdrawal', 'Withdrawal'), ('Transfer', 'Transfer')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.account')),
            ],
        ),
    ]
