# Generated by Django 5.0.1 on 2024-08-12 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_branch_collateral_task_account_checkingaccount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='manager',
        ),
    ]
