# Generated by Django 5.0.1 on 2024-08-13 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TempEmployee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('position', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_of_hire', models.DateField()),
                ('department', models.CharField(max_length=100)),
                ('statuse', models.BooleanField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_employees', to='polls.branch')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='temp_employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
