# Generated by Django 5.0.1 on 2024-08-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_tempemployee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempemployee',
            name='statuse',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
