# Generated by Django 5.1 on 2024-09-16 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_historicalroom_online_remove_room_online_room_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsavingsaccount',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='savingsaccount',
            name='end_date',
        ),
    ]
