# Generated by Django 5.1 on 2024-09-16 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_remove_historicalsavingsaccount_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaltransaction',
            old_name='account',
            new_name='form_account',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='account',
        ),
        migrations.AddField(
            model_name='historicaltransaction',
            name='to_account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='polls.account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='form_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_account_transactions', to='polls.account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='to_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_transactions', to='polls.account'),
        ),
    ]
