# Generated by Django 5.1.1 on 2024-09-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_alter_transaction_form_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalloan',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='historicalloan',
            name='start_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalloan',
            name='repayment_schedule',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='loan',
            name='repayment_schedule',
            field=models.IntegerField(),
        ),
    ]
