# Generated by Django 5.1.1 on 2024-09-23 11:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_alter_loan_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalloan',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='historicalloan',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='loan',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='loan',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='LoanPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(max_length=50)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.loan')),
            ],
        ),
    ]
