# Generated by Django 5.1.1 on 2024-09-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_historicalloanpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltaskassignment',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
