# Generated by Django 5.1.1 on 2024-09-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0023_historicaltaskassignment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalloan',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='loan',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
